%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/xiang/dataset/rgbd_dataset_freiburg1_desk

# camera intrinsics
# fr1
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

# fr2
#camera.fx: 520.9
#camera.fy: 521.0
#camera.cx: 325.1
#camera.cy: 249.7

camera.depth_scale: 5000

# VO Parameters
num_of_features: 500
scale_factor: 1.2
level_pyramid: 4